apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  labels:
    app: tetris-game
spec:
  type: LoadBalancer
  selector:
    app: tetris-game
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
