name: "Deploy EKS ManagedNG Layer"

on:
  push:
    branches:
      - main
    paths:
      - "EKS-Argocd-ManagedNodeRG/Infra/**"
      - ".github/workflows/deploy-eks-managedng.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "EKS-Argocd-ManagedNodeRG/Infra/**"
      - ".github/workflows/deploy-eks-managedng.yaml"
  workflow_dispatch:
    inputs:
      env-class:
        description: 'The environment class to deploy to'
        default: npd
        type: choice
        options:
        - npd
        - prd
      github-runner:
        description: 'Github runner to use, use ubuntu-latest when creating new environment. Defaults to '
        default: 'abc'
        type: choice
        options:
        - 'ubuntu-latest'
        - 'pe-arc-runner-shared-npd'
   

jobs:
  deploy-sbx-cluster:
    uses: AnoopHegde/platformengine-reusable-workflows/.github/workflows/terraform-aws-deploy.yaml@main
    with:
      github-env: npd
      environment: sbx
      working-directory: EKS-Argocd-ManagedNodeRG/Infra/terraform
      runner-label: ${{ inputs.github-runner || 'pe-arc-runner-shared-npd' }}
    secrets: inherit
